feat(rgbpp-sdk/btc): provide defult configs for testnet/mainnet
ckb-cell/rgbpp-sdk pull request #70
Opened 2024-03-29 03:53 UTC by ShookLyngs

## Main changes
1. Provide default configs (including dust limit for BTC/RGBPP UTXOs and more) for testnet and mainnet
2. Add actual dust limit validation in the `TxBuilder.addOutput()` method to prevent unexpected issues
3. Refactor P2WPKH transfer tests to a single recipient test, simplifying things
4. Set the default timeout of tests to 10 sec (suggested by @duanyytop)

## Details

### Dust limit on `MAINNET`

The dust limit of UTXOs on the mainnet should be set to `1,0000` instead of `1000` in the testnet. 

The PR differenciated the testnet/mainnet env and now provides configs for different network. When you're using the SDK on mainnet, you should transfer at least `1,0000` shannon to the recipient by default. For example, If th you try to define an output on the mainnet and its value < minUtxoSatoshi, the TxBuidler throws:

```
Error: Output defined value is below the dust limit: expected 10000, but defined 1000
```

2024-03-29 05:08 UTC, duanyytop commented on packages/btc/src/preset/network.ts
> +export function networkTypeToIsCkbMainnet(networkType: NetworkType): boolean {
The name of the `networkTypeToIsCkbMainnet` is a bit strange. Just make it simple and call it `checkIsCkbMainnet`.

2024-03-29 05:20 UTC, duanyytop commented on packages/btc/src/transaction/build.ts
> +      feeRate = this.feeRate!;
Changing function parameters directly is not good coding practice. You can use a new variable like this: 
```typescript
const txFeeRate = feeRate ?? this.feeRate!
```

2024-03-29 05:21 UTC, duanyytop approved these changes

2024-03-30 04:21 UTC, Flouse requested changes
I think `packages/btc/README.md` should be updated too.

2024-03-30 06:12 UTC, Flouse approved these changes

2024-03-30 06:13 UTC, merged